[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs = 4096

ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
solc = "0.8.24"
remappings = ["forge-std/=lib/forge-std/src/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
